// This file was autogenerated by web/third-party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/common/HttpRequest.js', ['WebMessenger.common.HttpRequest'], ['goog.events', 'goog.net.EventType', 'goog.net.XhrIo'], false);
goog.addDependency('../../../../js/enums/EventType.js', ['WebMessenger.enums.EventType'], [], false);
goog.addDependency('../../../../js/events/OnReceiveHistory.js', ['WebMessenger.events.OnReceiveHistory'], ['WebMessenger.enums.EventType', 'goog.events.Event'], false);
goog.addDependency('../../../../js/events/OnReceiveMessage.js', ['WebMessenger.events.OnReceiveMessage'], ['WebMessenger.enums.EventType', 'goog.events.Event'], false);
goog.addDependency('../../../../js/main.js', ['WebMessenger.App'], ['WebMessenger.enums.EventType', 'WebMessenger.models.DataModel', 'WebMessenger.services.ChatService'], false);
goog.addDependency('../../../../js/models/DataModel.js', ['WebMessenger.models.DataModel'], [], false);
goog.addDependency('../../../../js/services/ChatService.js', ['WebMessenger.services.ChatService'], ['WebMessenger.common.HttpRequest', 'WebMessenger.events.OnReceiveHistory', 'WebMessenger.events.OnReceiveMessage', 'goog.events.EventTarget'], false);
